#!/bin/sh

## get current value
CURR=$(defaults read com.apple.dock contents-immutable 2>/dev/null || echo '0') ##  0 || 1

## decide on new value
case $CURR in 0) NEW=true ;; 1) NEW=false ;; esac ##  true || false

## set new value
if [ $NEW = true ] || [ $NEW = false ]; then
  defaults write com.apple.dock contents-immutable -bool $NEW && killall Dock
fi
