#!/bin/sh

# shellcheck disable=SC1112 # Apostrophe

Vd='-d  Use Dock’s Documents side instead of Applications side'
Vs='-s  Use a small spacer'
# Vl='-l  run docklockle afterwards?'
Vh='-h  Print this help'

dUsage() {
  printf 'Usage:  %s [[-ds] | [-h]]\n' "$(basename "$0")"
}

dHelp() {
  printf 'Add spacer tiles to the Dock to group items.
%s
Options:
    %s.\n        Without options, a spacer is placed on Dock’s Applications side.
        Use this option to place the spacer on Dock’s Documents side instead.
    %s.\n        Without options, spacer has the same size as other icons in the Dock.
        Use this option to place a half-width small spacer instead.
    %s.\n' \
    "$(dUsage)" "${Vd}" "${Vs}" "${Vh}" && exit 0
}

illOptArg() {
  printf '\e[31m✘\e[0m Illegal option ignored.\n' >&2
  # %s\n  %s\n  %s\n  %s\n # "$(dUsage)" "${Vd}" "${Vs}" "${Vh}"
  #  %s\n "${Vl}"
}

if [ -n "$*" ]; then
  while getopts ':dsh' opt; do case ${opt} in
    d) side='others' ;; s) small=1 ;; h) dHelp ;; \?) ill=1 ;;
    esac; done
  # l # l) lockle=true ;;
  shift $((OPTIND - 1))
fi

if [ -n "${*}" ]; then
  illOptArg >&2
else
  if [ -n "${ill}" ]; then illOptArg >&2; fi
fi

defaults write 'com.apple.dock' persistent-"${side:-apps}" \
  -array-add '{tile-data={};tile-type='"${small:+small-}"'spacer-tile;}' && killall Dock

# if [ -n "${lockle}" ]; then "$(dirname "$0")"'/docklockle.sh'; fi
