#!/bin/sh

## get current value ## 0 || 1
curVAL=$(defaults read com.apple.dock contents-immutable)

## decide on new value ## true || false
case $curVAL in 0) newVAL=true;  printf   'locked\n' >&2 ;;
                1) newVAL=false; printf 'unlocked\n' >&2 ;; esac

## set new value 
defaults write com.apple.dock contents-immutable -bool $newVAL  &&  killall Dock
